apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-eval-main-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruleevalactorsystem
  template:
    metadata:
      labels:
        app: ruleevalactorsystem
    spec:
      containers:
        - name: ruleevalactorsystem
          image: surajgharat/rule-eval-main-service:6
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /alive
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          imagePullPolicy: Never
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 9000
              protocol: TCP
          env:
            - name: APPLICATION_SECRET
              value: 'abcdefghijklmnopqrstuvwxyz'
            - name: RUNTIME_MODE
              value: 'k8s'